package protocol

import (
	"context"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// This is a simplified protocol package for development
// In production, this would be generated from .proto files

// Metric represents a single metric
type Metric struct {
	Name      string
	Value     float64
	Timestamp int64
	Labels    map[string]string
	Type      MetricType
	Help      string
	Unit      string
}

// MetricType represents the type of metric
type MetricType int32

const (
	MetricType_GAUGE     MetricType = 0
	MetricType_COUNTER   MetricType = 1
	MetricType_HISTOGRAM MetricType = 2
	MetricType_SUMMARY   MetricType = 3
)

// RegisterRequest represents a node registration request
type RegisterRequest struct {
	NodeId     string
	Hostname   string
	Os         string
	Arch       string
	Version    string
	Labels     map[string]string
	Collectors []*CollectorInfo
}

// RegisterResponse represents a registration response
type RegisterResponse struct {
	Success           bool
	Message           string
	SessionId         string
	HeartbeatInterval int64
	Collectors        []*CollectorConfig
}

// CollectorInfo represents collector information
type CollectorInfo struct {
	Name     string
	Enabled  bool
	Interval int64
	Config   map[string]string
}

// CollectorConfig represents collector configuration
type CollectorConfig struct {
	Name     string
	Enabled  bool
	Interval int64
	Params   map[string]string
}

// MetricBatch represents a batch of metrics
type MetricBatch struct {
	NodeId    string
	SessionId string
	Metrics   []*Metric
	BatchSeq  int64
	SentAt    *timestamppb.Timestamp
}

// HeartbeatRequest represents a heartbeat request
type HeartbeatRequest struct {
	NodeId    string
	SessionId string
	Status    NodeStatus
}

// HeartbeatResponse represents a heartbeat response
type HeartbeatResponse struct {
	Alive         bool
	NextHeartbeat int64
}

// NodeStatus represents node health status
type NodeStatus int32

const (
	NodeStatus_HEALTHY   NodeStatus = 0
	NodeStatus_DEGRADED  NodeStatus = 1
	NodeStatus_UNHEALTHY NodeStatus = 2
)

// ControlMessage represents a control message to agents
type ControlMessage struct {
	// Command oneof
}

// ConfigUpdate represents a configuration update
type ConfigUpdate struct {
	NodeId          string
	ConfigYaml      string
	RestartRequired bool
}

// ConfigAck represents acknowledgment of config update
type ConfigAck struct {
	Success bool
	Message string
}

// MonitorService interface (normally generated by protoc)
type MonitorService interface {
	Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error)
	StreamMetrics(stream MonitorService_StreamMetricsServer) error
	Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatResponse, error)
	UpdateConfig(ctx context.Context, req *ConfigUpdate) (*ConfigAck, error)
}

// MonitorService_StreamMetricsServer is the server stream interface
type MonitorService_StreamMetricsServer interface {
	Send(*ControlMessage) error
	Recv() (*MetricBatch, error)
	Context() context.Context
}

// RegisterMonitorServiceServer registers the monitor service
func RegisterMonitorServiceServer(s interface{}, srv MonitorService) {
	// This is normally generated by protoc
	// For now, it's a no-op as we're using simplified implementations
}
